"""Supervision package.

Hosts the three Codex-role pipeline:

- ``answer_supervisor``: hidden-reference evaluator.
- ``user_simulator``: public-feedback generator.
- ``feedback_rewriter``: assembles the safe user-visible feedback.
- ``orchestrator``: ``run_supervisor`` — drives the three roles sequentially.

``common`` aggregates the shared primitives (dataclasses, codex config, role
workspace prep, transcript / image helpers). It replaces the old
``lib/supervision_common.py`` module; the shim there now just re-exports
from this package.
"""
from __future__ import annotations

from .common import (
    # constants
    CONTAINER_CODEX_HOME,
    CONTAINER_RUNTIME_DIR,
    CONTAINER_SESSION_ROOT,
    CONTAINER_WORKDIR,
    DEFAULT_CODEX_CONFIG,
    DEFAULT_CODEX_IMAGE,
    DEFAULT_CODEX_MAX_ATTEMPTS,
    DEFAULT_CODEX_RETRY_BACKOFF_SECONDS,
    DEFAULT_CODEX_TIMEOUT_SECONDS,
    EDICT_AGENT_LABELS,
    LEGACY_CODEX_BIN,
    ROOT,
    TOOLLESS_RETRY_NEEDLES,
    TRANSIENT_CODEX_ERROR_NEEDLES,
    # dataclasses
    AttemptSupervisorContext,
    CodexRoleRuntimeContext,
    SupervisorContext,
    TaskSupervisorContext,
    # text + file utilities
    clamp_score,
    coerce_text_list,
    copy_file_into,
    copy_supervisor_asset,
    copy_tree_into,
    file_kind,
    read_json,
    read_text,
    reset_dir,
    sanitize_codex_context_text,
    summarize_file,
    summarize_result_dir,
    write_json,
    # transcript + evidence
    build_agent_session_summaries,
    build_handoff_trace,
    build_hidden_payload,
    build_multi_agent_visible_payload,
    build_visible_payload,
    collect_image_ocr_blocks,
    collect_reference_images,
    collect_reference_text_blocks,
    collect_visible_images,
    extract_image_ocr_text,
    image_ocr_cache_path,
    load_agent_manifest,
    operation_trace_summary,
    parse_agent_session_target,
    parse_first_json_object,
    primary_eval_rule_block,
    prompt_context_text,
    redacted_supervision_context,
    resolve_reference_path,
    runtime_probe_payload,
    semantic_transcript_blocks,
    summarize_recent_tool_calls,
    _strip_edict_routing_note,
    # codex config + execution
    build_codex_execution_prompt,
    build_session_prompt,
    codex_env_file_candidates,
    codex_env_keys,
    codex_retry_backoff_seconds,
    codex_rollout_summary,
    ensure_isolated_codex_home,
    is_transient_codex_error,
    latest_codex_rollout_log,
    load_codex_base_config,
    render_codex_config,
    render_template,
    required_codex_env_keys,
    resolve_codex_env_vars,
    resolve_codex_provider,
    run_codex_prompt,
    run_codex_via_container,
    session_path_to_container,
    should_force_toolless_retry,
    # workspace preparation
    append_role_history,
    build_role_workspace_readme,
    load_role_history,
    prepare_role_workspace,
    role_history_path,
    role_home_dir,
    role_runtime_dir,
    role_session_dir,
    role_workspace_dir,
    _role_workspace_prompt_files,
)
from .answer_supervisor import (
    ANSWER_SUPERVISOR_OUTPUT_SCHEMA,
    build_answer_supervisor_prompt,
    run_answer_supervisor,
    validate_answer_supervisor_payload,
)
from .feedback_rewriter import (
    fallback_feedback,
    is_completion_line,
    rewrite_feedback,
    split_candidate_lines,
)
from .orchestrator import (
    build_public_feedback,
    run_supervisor,
)
from .user_simulator import (
    USER_SIMULATOR_OUTPUT_SCHEMA,
    build_user_simulator_prompt,
    run_public_user_simulator,
    validate_user_simulator_payload,
)

__all__ = [
    "ANSWER_SUPERVISOR_OUTPUT_SCHEMA",
    "AttemptSupervisorContext",
    "CONTAINER_CODEX_HOME",
    "CONTAINER_RUNTIME_DIR",
    "CONTAINER_SESSION_ROOT",
    "CONTAINER_WORKDIR",
    "CodexRoleRuntimeContext",
    "DEFAULT_CODEX_CONFIG",
    "DEFAULT_CODEX_IMAGE",
    "DEFAULT_CODEX_MAX_ATTEMPTS",
    "DEFAULT_CODEX_RETRY_BACKOFF_SECONDS",
    "DEFAULT_CODEX_TIMEOUT_SECONDS",
    "EDICT_AGENT_LABELS",
    "LEGACY_CODEX_BIN",
    "ROOT",
    "SupervisorContext",
    "TOOLLESS_RETRY_NEEDLES",
    "TRANSIENT_CODEX_ERROR_NEEDLES",
    "TaskSupervisorContext",
    "USER_SIMULATOR_OUTPUT_SCHEMA",
    "append_role_history",
    "build_agent_session_summaries",
    "build_answer_supervisor_prompt",
    "build_codex_execution_prompt",
    "build_handoff_trace",
    "build_hidden_payload",
    "build_multi_agent_visible_payload",
    "build_public_feedback",
    "build_role_workspace_readme",
    "build_session_prompt",
    "build_user_simulator_prompt",
    "build_visible_payload",
    "clamp_score",
    "codex_env_file_candidates",
    "codex_env_keys",
    "codex_retry_backoff_seconds",
    "codex_rollout_summary",
    "coerce_text_list",
    "collect_image_ocr_blocks",
    "collect_reference_images",
    "collect_reference_text_blocks",
    "collect_visible_images",
    "copy_file_into",
    "copy_supervisor_asset",
    "copy_tree_into",
    "ensure_isolated_codex_home",
    "extract_image_ocr_text",
    "fallback_feedback",
    "file_kind",
    "image_ocr_cache_path",
    "is_completion_line",
    "is_transient_codex_error",
    "latest_codex_rollout_log",
    "load_agent_manifest",
    "load_codex_base_config",
    "load_role_history",
    "operation_trace_summary",
    "parse_agent_session_target",
    "parse_first_json_object",
    "prepare_role_workspace",
    "primary_eval_rule_block",
    "prompt_context_text",
    "read_json",
    "read_text",
    "redacted_supervision_context",
    "render_codex_config",
    "render_template",
    "required_codex_env_keys",
    "reset_dir",
    "resolve_codex_env_vars",
    "resolve_codex_provider",
    "resolve_reference_path",
    "rewrite_feedback",
    "role_history_path",
    "role_home_dir",
    "role_runtime_dir",
    "role_session_dir",
    "role_workspace_dir",
    "run_answer_supervisor",
    "run_codex_prompt",
    "run_codex_via_container",
    "run_public_user_simulator",
    "run_supervisor",
    "runtime_probe_payload",
    "sanitize_codex_context_text",
    "semantic_transcript_blocks",
    "session_path_to_container",
    "should_force_toolless_retry",
    "split_candidate_lines",
    "summarize_file",
    "summarize_recent_tool_calls",
    "summarize_result_dir",
    "validate_answer_supervisor_payload",
    "validate_user_simulator_payload",
    "write_json",
]
# Underscore-prefixed helpers (``_normalize_answer_decision``,
# ``_role_workspace_prompt_files``, ``_strip_edict_routing_note``) and the
# ``dedupe_lines`` shim are intentionally NOT in ``__all__`` — they are
# package-internal and the few external callers (tests) deep-import from the
# defining module (e.g. ``from lib.supervision.orchestrator import _normalize_answer_decision``).
# Keeping them off the surface API prevents accidental "from lib.supervision import *"
# leakage of names that were never meant to be public.
